### PR TITLE
pgBadger Parameter Updates

### PR DESCRIPTION
**Pull request by sheyd**
* Removes old Quasar QA `quasar-qa` Postgres 10 based parameter group, since we no longer use it.
* Updates some Quasar QA Postgres 11 parameters required for use [in pgBadger](https://www.pivotaltracker.com/story/show/167350014/comments/205197976).

### CODE REVIEW

**Comment by sheyd** [comment]
@DFurnes Ugh, sorry, I didn't do separate commits for removing old PG10 group, _then_ updating with new values so the diffs are kind of confusing and gnarly. If you'd like to keep consistency, I can delete this branch and re-do the commits in a better order. Let me know!

**Comment by DFurnes** [comment]
Yeah, I'm having a hard time making sense of this diff. Mind cleaning it up? 🙇

**Comment by sheyd** [comment]
Okay! Separated into 2 commits:

* [Cleanup of old Postgres 10 param group](https://github.com/DoSomething/infrastructure/pull/196/commits/fc910cb37609f8ed6af5bd8c7f7c4a08be4dd83d).
* [Adding pgBadger required params to Postgres 11 Quasar QA group](https://github.com/DoSomething/infrastructure/pull/196/commits/91dc7bf374db01d7389454fc666314aecb2ff107).

**Comment by sheyd** [comment]
Also, all these parameters are dynamic so no need for DB restart!

**Pull request merged**
