### PR TITLE
WIP: Extract base modules for each app, composed of shared components.

### PR DESCRIPTION
**Pull request by DFurnes**
This pull request starts applying the same treatment that Longshot got in DoSomething/infrastructure#28 to other applications.

🙈 Adds an `ignore_web` flag to the base `laravel_app` module so that we can tell Terraform not to manage web dynos for some apps, since [it doesn't currently support auto-scaling](https://github.com/DoSomething/infrastructure/issues/7). 6a67892

📂 Moves the `longshot/application` module into `applications/longshot`, where it can live alongside our other environment-agnostic application templates. fc083d0

✨ Creates a shared `applications/northstar` module to build each Northstar app. 332886b

### CODE REVIEW

**Comment by DFurnes** [comment]
I've extracted a bare-bones `application/northstar` module in 332886b & updated state to point to the same resources we already have in production so they don't need to be re-built.

This will set a per-environment `APP_ENV` and start managing New Relic environment variables with Terraform (so halfway for #60). The `CACHE_DRIVER` and `SESSION_DRIVER` config vars are no-ops, but weren't previously tracked with Terraform. Finally, there's a brief reset to Northstar QA's scaling that I'll reset to full beefiness so it doesn't affect Rafa's load testing. 🍖 

Here's the plan:

```
~ module.dosomething-dev.module.northstar.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "development"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething-qa.module.northstar.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "qa"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething-qa.module.northstar.module.app.heroku_formation.web
    quantity:   "5" => "1"
    size:       "Performance-M" => "Standard-1X"

~ module.dosomething.module.northstar.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_APP_NAME:           "" => "dosomething-northstar"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "true"
    config_vars.0.NEW_RELIC_LICENSE_KEY:        "" => "***** SECRET *****"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"
```

**Comment by DFurnes** [comment]
Same deal for Rogue in 344e97e. As with Northstar, we add config vars that were previously not managed by Terraform into state. I'm also scaling `dosomething-northstar-dev` up to `Standard-1x` dynos for consistency with our other QA environments:

```
~ module.dosomething-dev.module.rogue.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "development"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething-dev.module.rogue.module.app.heroku_formation.queue
    size:   "Hobby" => "Standard-1X"

~ module.dosomething-dev.module.rogue.module.app.heroku_formation.web
    size:   "Hobby" => "Standard-1X"

~ module.dosomething-qa.module.rogue.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "qa"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething.module.rogue.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_APP_NAME:           "" => "dosomething-rogue"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "true"
    config_vars.0.NEW_RELIC_LICENSE_KEY:        "" => "***** SECRET *****"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething.module.rogue.module.app.heroku_formation.queue
    quantity:   "2" => "1"
```

**Comment by DFurnes** [comment]
And finally, added Phoenix in 3ec5834. As part of this change, I'm removing Phoenix from the "Backends (QA)" Fastly property, since it doesn't serve as a backend (and it was confusing to have it accessible as qa.dosomething.org as a frontend, but www-qa.dosomething.org as a backend! 🤔 Instead, I've updated www-qa.dosomething.org to redirect to qa.dosomething.org.

```
~ module.dosomething-qa.module.fastly-backend.fastly_service_v1.backends-qa
    backend.#:                                  "4" => "3"
    backend.3526671977.ssl_client_cert:         "<sensitive>" => "<sensitive>" (attribute changed)
    backend.3526671977.ssl_client_key:          "<sensitive>" => "<sensitive>" (attribute changed)
    backend.3951543755.ssl_client_cert:         "<sensitive>" => "<sensitive>" (attribute changed)
    backend.3951543755.ssl_client_key:          "<sensitive>" => "<sensitive>" (attribute changed)
    backend.619130907.ssl_client_cert:          "<sensitive>" => "<sensitive>" (attribute changed)
    backend.619130907.ssl_client_key:           "<sensitive>" => "<sensitive>" (attribute changed)
    backend.879700407.address:                  "dosomething-phoenix-qa.herokuapp.com" => ""
    backend.879700407.between_bytes_timeout:    "10000" => "0"
    backend.879700407.connect_timeout:          "1000" => "0"
    backend.879700407.first_byte_timeout:       "15000" => "0"
    backend.879700407.max_conn:                 "200" => "0"
    backend.879700407.name:                     "dosomething-phoenix-qa" => ""
    backend.879700407.port:                     "443" => "0"
    backend.879700407.request_condition:        "backend-phoenix-qa" => ""
    backend.879700407.shield:                   "iad-va-us" => ""
    backend.879700407.ssl_check_cert:           "true" => "false"
    backend.879700407.weight:                   "100" => "0"
    condition.#:                                "9" => "7"
    condition.2708961863.name:                  "backend-phoenix-qa" => ""
    condition.2708961863.priority:              "10" => "0"
    condition.2708961863.statement:             "req.http.host == "www-qa.dosomething.org"" => ""
    condition.2708961863.type:                  "REQUEST" => ""
    condition.3165446876.name:                  "response-phoenix-qa" => ""
    condition.3165446876.priority:              "10" => "0"
    condition.3165446876.statement:             "req.http.host == "www-qa.dosomething.org"" => ""
    condition.3165446876.type:                  "RESPONSE" => ""
    domain.#:                                   "4" => "3"
    domain.2223411740.name:                     "www-qa.dosomething.org" => ""
    papertrail.#:                               "4" => "3"
    papertrail.2266851864.address:              "*** SECRET ***" => ""
    papertrail.2266851864.format:               "%t '%r' status=%>s cache=%{X-Cache}o country=%{X-Fastly-Country-Code}o bytes=%b microseconds=%D" => ""
    papertrail.2266851864.name:                 "phoenix-qa" => ""
    papertrail.2266851864.port:                 "*** SECRET ***" => "0"
    papertrail.2266851864.response_condition:   "response-phoenix-qa" => ""

~ module.dosomething-dev.module.phoenix.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "development"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething-qa.module.phoenix.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "qa"
    config_vars.0.APP_URL:                      "https://www-qa.dosomething.org" => "https://qa.dosomething.org"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething.module.phoenix.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_APP_NAME:           "" => "dosomething-phoenix"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "true"
    config_vars.0.NEW_RELIC_LICENSE_KEY:        "" => "ccecf2f2af8550847388e05fdabed29187236856"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething.module.phoenix_preview.module.app.heroku_addon.redis
    plan:   "heroku-redis:hobby-dev" => "heroku-redis:premium-1"

~ module.dosomething.module.phoenix_preview.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_APP_NAME:           "" => "dosomething-phoenix-preview"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "true"
    config_vars.0.NEW_RELIC_LICENSE_KEY:        "" => "ccecf2f2af8550847388e05fdabed29187236856"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"
```

**Comment by DFurnes** [comment]
And finally, added Phoenix in 3ec5834. As part of this change, I'm removing Phoenix from the "Backends (QA)" Fastly property, since it doesn't serve as a backend (and it was confusing to have it accessible as qa.dosomething.org as a frontend, but www-qa.dosomething.org as a backend! 🤔 Instead, I'll update www-qa.dosomething.org to redirect to qa.dosomething.org.

```
~ module.dosomething-qa.module.fastly-backend.fastly_service_v1.backends-qa
    backend.#:                                  "4" => "3"
    backend.3526671977.ssl_client_cert:         "<sensitive>" => "<sensitive>" (attribute changed)
    backend.3526671977.ssl_client_key:          "<sensitive>" => "<sensitive>" (attribute changed)
    backend.3951543755.ssl_client_cert:         "<sensitive>" => "<sensitive>" (attribute changed)
    backend.3951543755.ssl_client_key:          "<sensitive>" => "<sensitive>" (attribute changed)
    backend.619130907.ssl_client_cert:          "<sensitive>" => "<sensitive>" (attribute changed)
    backend.619130907.ssl_client_key:           "<sensitive>" => "<sensitive>" (attribute changed)
    backend.879700407.address:                  "dosomething-phoenix-qa.herokuapp.com" => ""
    backend.879700407.between_bytes_timeout:    "10000" => "0"
    backend.879700407.connect_timeout:          "1000" => "0"
    backend.879700407.first_byte_timeout:       "15000" => "0"
    backend.879700407.max_conn:                 "200" => "0"
    backend.879700407.name:                     "dosomething-phoenix-qa" => ""
    backend.879700407.port:                     "443" => "0"
    backend.879700407.request_condition:        "backend-phoenix-qa" => ""
    backend.879700407.shield:                   "iad-va-us" => ""
    backend.879700407.ssl_check_cert:           "true" => "false"
    backend.879700407.weight:                   "100" => "0"
    condition.#:                                "9" => "7"
    condition.2708961863.name:                  "backend-phoenix-qa" => ""
    condition.2708961863.priority:              "10" => "0"
    condition.2708961863.statement:             "req.http.host == "www-qa.dosomething.org"" => ""
    condition.2708961863.type:                  "REQUEST" => ""
    condition.3165446876.name:                  "response-phoenix-qa" => ""
    condition.3165446876.priority:              "10" => "0"
    condition.3165446876.statement:             "req.http.host == "www-qa.dosomething.org"" => ""
    condition.3165446876.type:                  "RESPONSE" => ""
    domain.#:                                   "4" => "3"
    domain.2223411740.name:                     "www-qa.dosomething.org" => ""
    papertrail.#:                               "4" => "3"
    papertrail.2266851864.address:              "*** SECRET ***" => ""
    papertrail.2266851864.format:               "%t '%r' status=%>s cache=%{X-Cache}o country=%{X-Fastly-Country-Code}o bytes=%b microseconds=%D" => ""
    papertrail.2266851864.name:                 "phoenix-qa" => ""
    papertrail.2266851864.port:                 "*** SECRET ***" => "0"
    papertrail.2266851864.response_condition:   "response-phoenix-qa" => ""

~ module.dosomething-dev.module.phoenix.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "development"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething-qa.module.phoenix.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.APP_ENV:                      "production" => "qa"
    config_vars.0.APP_URL:                      "https://www-qa.dosomething.org" => "https://qa.dosomething.org"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "false"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething.module.phoenix.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_APP_NAME:           "" => "dosomething-phoenix"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "true"
    config_vars.0.NEW_RELIC_LICENSE_KEY:        "" => "***** SECRET *****"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"

~ module.dosomething.module.phoenix_preview.module.app.heroku_addon.redis
    plan:   "heroku-redis:hobby-dev" => "heroku-redis:premium-1"

~ module.dosomething.module.phoenix_preview.module.app.heroku_app.app
    config_vars.0.%:                            "4" => "11"
    config_vars.0.CACHE_DRIVER:                 "" => "redis"
    config_vars.0.NEW_RELIC_APP_NAME:           "" => "dosomething-phoenix-preview"
    config_vars.0.NEW_RELIC_ENABLED:            "" => "true"
    config_vars.0.NEW_RELIC_LICENSE_KEY:        "" => "***** SECRET *****"
    config_vars.0.NEW_RELIC_LOG_LEVEL:          "" => "error"
    config_vars.0.SESSION_DRIVER:               "" => "redis"
    config_vars.0.TRUSTED_PROXY_IP_ADDRESSES:   "" => "**"
```

**Comment by DFurnes** [comment]
Alright @sheyd, this is ready for review! 👁

**Comment by sheyd** [comment]
And this is such a good re-factoring!

**Comment by DFurnes** [comment]
Thanks again for taking the time to review this @sheyd! I've applied & everything seems 💯 on prod.

**Pull request merged**
