### PR TITLE
Quasar Prod Setup

### PR DESCRIPTION
**Pull request by sheyd**
* Adds Quasar Prod RDS instance as a resource.
* Adds Quasar Prod Param group.

### CODE REVIEW

**Comment by sheyd** [comment]
<details>
     <summary>Planned Changes</summary>

```
~ module.quasar.aws_db_instance.quasar
    parameter_group_name:   "postgres10-repl" => "${aws_db_parameter_group.quasar-prod.id}"
    skip_final_snapshot:    "true" => "false"
    tags.%:                 "1" => "0"
    tags.workload-type:     "production" => ""

+ module.quasar.aws_db_parameter_group.quasar-prod
    id:                                  "<computed>"
    arn:                                 "<computed>"
    description:                         "Managed by Terraform"
    family:                              "postgres10"
    name:                                "quasar-prod"
    name_prefix:                         "<computed>"
    parameter.#:                         "5"
    parameter.1628013253.apply_method:   "immediate"
    parameter.1628013253.name:           "work_mem"
    parameter.1628013253.value:          "17476"
    parameter.2198120102.apply_method:   "pending-reboot"
    parameter.2198120102.name:           "rds.logical_replication"
    parameter.2198120102.value:          "1"
    parameter.3496613493.apply_method:   "immediate"
    parameter.3496613493.name:           "effective_cache_size"
    parameter.3496613493.value:          "48000000"
    parameter.706871880.apply_method:    "pending-reboot"
    parameter.706871880.name:            "max_logical_replication_workers"
    parameter.706871880.value:           "500"
    parameter.752387658.apply_method:    "immediate"
    parameter.752387658.name:            "maintenance_work_mem"
    parameter.752387658.value:           "2000000"
```

</details>

**Comment by sheyd** [comment]
Before running the `make plan`, I ran `terraform import module.quasar.aws_db_instance.quasar quasar-prod` to import existing Production instance.

**Comment by sheyd** [comment]
Ooo, I like that idea 👍. https://github.com/DoSomething/infrastructure/issues/73 created for this!

**Comment by sheyd** [comment]
Changes applied successfully.

**Comment by DFurnes** [comment]
References #48.

**Pull request merged**
