### PR TITLE
Quasar VPN Endpoint

### PR DESCRIPTION
**Pull request by sheyd**
This PR creates the VPN endpoint for use in the Quasar environment.

### CODE REVIEW

**Comment by sheyd** [comment]
Output of `make plan`:
```
Terraform will perform the following actions:

  # module.quasar.aws_ec2_client_vpn_endpoint.quasar-vpn-endpoint will be created
  + resource "aws_ec2_client_vpn_endpoint" "quasar-vpn-endpoint" {
      + client_cidr_block      = "172.22.0.0/22"
      + description            = "Quasar-Client-VPN"
      + dns_name               = (known after apply)
      + id                     = (known after apply)
      + server_certificate_arn = "arn:aws:acm:us-east-1:389428637636:certificate/e9f30bbd-f33d-4f0f-a3d9-7c1045bab8a1"
      + split_tunnel           = true
      + status                 = (known after apply)
      + transport_protocol     = "udp"

      + authentication_options {
          + type = "certificate-authentication"
        }

      + connection_log_options {
          + enabled = true
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by sheyd** [comment]
Hit this error on creation:
```
Error: Error creating Client VPN endpoint: MissingParameter: Client root certificate arn is required but is missing in the request
	status code: 400, request id: *****
```
[This commit](https://github.com/DoSomething/infrastructure/pull/209/commits/6e973b016c6c26f6f6bbfe6d099dcb0cff721908) should fix it.

**Comment by sheyd** [comment]
Yet another errors:
```
Error: Error creating Client VPN endpoint: MissingParameter: Please provide a cloudwatch log group
	status code: 400, request id: *****

  on quasar/main.tf line 487, in resource "aws_ec2_client_vpn_endpoint" "quasar-vpn-endpoint":
 487: resource "aws_ec2_client_vpn_endpoint" "quasar-vpn-endpoint" {
```

Looks like [we need](https://www.terraform.io/docs/providers/aws/r/ec2_client_vpn_endpoint.html#authentication_options-argument-reference) both optional Cloudwatch arguments. @DFurnes any preference on where these should flow to auto-propagate them into existing Cloudwatch/Papertrail system?

**Comment by DFurnes** [comment]
You can follow the approach for [our other Lambda functions](https://github.com/DoSomething/infrastructure/blob/dfd5b2fedf93ce5050c8dec5d0b52d9acbe6f42c/components/lambda_function/main.tf#L51-L67) for configuring the connection, and it's probably best to create a new Papertrail forwarder for Quasar [like we do for production](https://github.com/DoSomething/infrastructure/blob/dfd5b2fedf93ce5050c8dec5d0b52d9acbe6f42c/dosomething/main.tf#L124-L130) (since we've been treating Quasar as it's own entirely separate ecosystem).

**Comment by DFurnes** [comment]
Ehhh although that also means we'd have to add that [as a fourth deploy target](https://github.com/DoSomething/lambda-papertrail/blob/ddb729e1f59e8e02dd1fa72f81fde6e693a57c80/.circleci/config.yml#L60-L67)... so maybe we should just use the existing production Lambda. It might be worth just extracting that production one to the root level & passing it in to both `dosomething` and `quasar` modules.

**Comment by DFurnes** [comment]
I set a `null` default value for the Papertrail module argument (so Terraform can differentiate whether the module does or doesn't exist without running an apply).

I then had to do the same lil' shuffle as in https://github.com/DoSomething/infrastructure/pull/195#issuecomment-511513880 to create the placeholder "null" module before moving the existing Papertrail module to it's new home:

```
echo 'resource "null_resource" "null" {}' > applications/papertrail/main.tf
terraform apply -target=module.papertrail.null_resource.null
terraform state mv module.dosomething.module.papertrail module.papertrail
```

**Comment by DFurnes** [comment]
Looking happy to me after those changes:

```
Terraform will perform the following actions:

  # module.quasar.aws_cloudwatch_log_group.log_group will be created
  + resource "aws_cloudwatch_log_group" "log_group" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/lambda/papertrail"
      + retention_in_days = 14
    }

  # module.quasar.aws_cloudwatch_log_subscription_filter.papertrail_subscription will be created
  + resource "aws_cloudwatch_log_subscription_filter" "papertrail_subscription" {
      + destination_arn = "*****"
      + distribution    = "ByLogStream"
      + id              = (known after apply)
      + log_group_name  = "/aws/lambda/papertrail"
      + name            = "papertrail_forwarder"
      + role_arn        = (known after apply)
    }

  # module.quasar.aws_ec2_client_vpn_endpoint.quasar-vpn-endpoint will be created
  + resource "aws_ec2_client_vpn_endpoint" "quasar-vpn-endpoint" {
      + client_cidr_block      = "172.22.0.0/22"
      + description            = "Quasar-Client-VPN"
      + dns_name               = (known after apply)
      + id                     = (known after apply)
      + server_certificate_arn = "*****"
      + split_tunnel           = true
      + status                 = (known after apply)
      + transport_protocol     = "udp"

      + authentication_options {
          + root_certificate_chain_arn = "*****"
          + type                       = "certificate-authentication"
        }

      + connection_log_options {
          + cloudwatch_log_group = "/aws/lambda/papertrail"
          + enabled              = true
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

**Comment by sheyd** [comment]
Sweet! Can I `make apply` and merge?

**Comment by sheyd** [comment]
Thanks for you help on this Dave!! <3

**Comment by DFurnes** [comment]
> Sweet! Can I `make apply` and merge?

Yeah, go for it! 🚀

**Comment by sheyd** [comment]
Mostly got there, but permissions error popped up:
```
Error: Error creating Cloudwatch log subscription filter: InvalidParameterException: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
	status code: 400, request id: 7b05a159-0d40-4a5b-b6a2-e82b3376b98a

  on quasar/main.tf line 495, in resource "aws_cloudwatch_log_subscription_filter" "papertrail_subscription":
 495: resource "aws_cloudwatch_log_subscription_filter" "papertrail_subscription" {
```

**Comment by sheyd** [comment]
@DFurnes For the last error, I'm a little confused. Does the manually defined block:
```
resource "aws_cloudwatch_log_group" "log_group" {
  name              = "/aws/vpn/quasar"
  retention_in_days = 14
}
```

Require an actual lambda function? Or maybe it needs to be part of the `/aws/lambda/*` group? I looked at the permissions in IAM, but couldn't find a starting point to track down the permissions for this. Can you point me in the right direction?

**Comment by DFurnes** [comment]
@sheyd Ahh yeah, you need to give the CloudWatch log group permission to invoke the Papertrail "logger" Lambda function. Try adding this to the Quasar module:

```terraform
resource "aws_lambda_permission" "allow_cloudwatch" {
  count = var.logger == "" ? 0 : 1

  action        = "lambda:InvokeFunction"
  function_name = var.papertrail_forwarder.arn
  principal     = "logs.us-east-1.amazonaws.com"
  source_arn    = aws_cloudwatch_log_group.log_group.arn
}
```

**Comment by sheyd** [comment]
@DFurnes Can you take a quick 👀 at [this](https://github.com/DoSomething/infrastructure/pull/209/commits/00e502dff28f2363c405203f4bfe310ea25e832d) and [this](https://github.com/DoSomething/infrastructure/pull/209/files#diff-9c2578982d1e7190ae7d08c9f7b03e61R495-R517) to verify looks good? 

Output of `make plan`:
```
Terraform will perform the following actions:

  # module.quasar.aws_cloudwatch_log_subscription_filter.papertrail_subscription will be created
  + resource "aws_cloudwatch_log_subscription_filter" "papertrail_subscription" {
      + destination_arn = "******"
      + distribution    = "ByLogStream"
      + id              = (known after apply)
      + log_group_name  = "/aws/vpn/quasar"
      + name            = "papertrail_forwarder"
      + role_arn        = (known after apply)
    }

  # module.quasar.aws_ec2_client_vpn_endpoint.quasar-vpn-endpoint will be updated in-place
  ~ resource "aws_ec2_client_vpn_endpoint" "quasar-vpn-endpoint" {
        client_cidr_block      = "172.22.0.0/22"
        description            = "Quasar-Client-VPN"
        dns_name               = "********"
        id                     = "cvpn-endpoint-09124d7307e277c34"
        server_certificate_arn = "********"
        split_tunnel           = true
        tags                   = {}
        transport_protocol     = "udp"

        authentication_options {
            root_certificate_chain_arn = "*******"
            type                       = "certificate-authentication"
        }

      ~ connection_log_options {
            cloudwatch_log_group  = "/aws/vpn/quasar"
          - cloudwatch_log_stream = "******* -> null
            enabled               = true
        }
    }

  # module.quasar.aws_lambda_permission.allow_cloudwatch[0] will be created
  + resource "aws_lambda_permission" "allow_cloudwatch" {
      + action        = "lambda:InvokeFunction"
      + function_name = "arn:aws:lambda:******"
      + id            = (known after apply)
      + principal     = "logs.us-east-1.amazonaws.com"
      + source_arn    = "arn:aws:logs:us-east-1:******"
      + statement_id  = (known after apply)
    }

Plan: 2 to add, 1 to change, 0 to destroy.

**Comment by sheyd** [comment]
Finally went thru successfully!

**Pull request merged**
