### PR TITLE
Quasar QA Param Group

### PR DESCRIPTION
**Pull request by sheyd**
PR to test and roll-out Quasar DB Tuning parameters for QA, related to: https://www.pivotaltracker.com/story/show/162208643

### CODE REVIEW

**Comment by sheyd** [comment]
<details>
    <summary>planned changes</summary>

```
~ module.quasar.aws_db_instance.quasar-qa
    parameter_group_name:   "quasar" => "${aws_db_parameter_group.quasar-qa.id}"

-/+ module.quasar.aws_db_parameter_group.quasar-qa (new resource required)
    id:                                  "quasar" => "<computed>" (forces new resource)
    arn:                                 "arn:aws:rds:us-east-1:389428637636:pg:quasar" => "<computed>"
    name:                                "quasar" => "quasar-qa" (forces new resource)
    name_prefix:                         "" => "<computed>"
    parameter.#:                         "2" => "5"
    parameter.3902169697.apply_method:   "" => "immediate"
    parameter.3902169697.name:           "" => "work_mem"
    parameter.3902169697.value:          "" => "20971"
    parameter.4108286640.apply_method:   "" => "immediate"
    parameter.4108286640.name:           "" => "effective_cache_size"
    parameter.4108286640.value:          "" => "24000000"
    parameter.752387658.apply_method:    "" => "immediate"
    parameter.752387658.name:            "" => "maintenance_work_mem"
    parameter.752387658.value:           "" => "2000000"
```

</details>

**Comment by sheyd** [comment]
Changes successfully applied!

**Comment by sheyd** [comment]
Descriptions added, too.

**Comment by DFurnes** [comment]
References #48.

**Pull request merged**
